/*
    Generated by Atomist on 05 07 2016 
*/
package tpinternal;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MicrocourseApplication {

    public static void main(String[] args) {
        SpringApplication.run(MicrocourseApplication.class, args);
    }
}
